kind: Service
apiVersion: v1
metadata:
  name: echo-service
  labels:
    app: echo-service
spec:
  selector:
    app: echo-service
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service
  labels:
    app: echo-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-service
  template:
    metadata:
      labels:
        app: echo-service
    spec:
      containers:
      - name: echo-service
        image: spatnaik77/echo-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP